server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

client:
  urls:
    ms-auth: http://localhost:8282